NKRO_ENABLE = yes
AUTOCORRECT_ENABLE = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
COMBO_ENABLE = yes
DEFAULT_FOLDER = sofle/darthtux
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
# Enable DBug Mode
CONSOLE_ENABLE = no